### ISSUE TITLE
New output: metadata including statistics

### ISSUE THREAD

**Issue by mhebing** [ddionrails/soep-test#21]
```
...
- label: asdjflkjas
  name: ajsdfklj
  type: number
  statistics:
    min: 5
    max: 10
    mean 7
- ...
  type: categorical
  labellist:
  - value: 1
    label: asdf
    freq: 23
  - value: 2
    label: asdf
    freq: 4
...
```
